version: '3.6'
services:
    config:
        build:
            context: ./config
            dockerfile: Dockerfile
        image: config:1.0
        container_name: "config"
        networks:
            - jp_network
        ports:
            - 8888:8888
        hostname: config

    discovery:
        build:
            context: ./discovery
            dockerfile: Dockerfile
        image: discovery:1.0
        container_name: "discovery"
        networks:
            - jp_network
        restart: on-failure
        ports:
            - 4000:4000
        hostname: discovery

    proxy:
        build:
            context: ./proxy
            dockerfile: Dockerfile
        image: proxy:1.0
        container_name: "proxy"
        restart: on-failure
        networks:
            - jp_network
        ports:
            - 5000:5000
        depends_on:
            - "config"
            - "discovery"
        hostname: proxy

    add:
        build:
            context: ./add
            dockerfile: Dockerfile
        image: add:1.0
        container_name: "add"
        restart: on-failure
        networks:
            - jp_network
        ports:
            - 4001:4001
        depends_on:
            - "config"
            - "discovery"
            - "proxy"
        hostname: add

networks:
    jp_network:
        name: jp_network
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
