version: '3.0'
services:
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: admin@1
    image: config-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
    image: registry-service
    restart: always
    ports:
      - 1901:1901
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: admin@1
    image: proxy-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 1800:1800
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  addservice:
    environment:
      CONFIG_SERVICE_PASSWORD: admin@1
    image: addservice
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  multiplyservice:
    environment:
      CONFIG_SERVICE_PASSWORD: admin@1
    image: multiservice
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"
